Add more clipboard format options
flameshot-org/flameshot pull request #1750
Opened 2021-07-24 12:24 UTC by thetaprimeprime

This is mainly to fix #1738 .

Because some programs only detect particular image formats in clipboard.
For example, xfreerdp only accepts BMP, but Firefox prefers PNG.

If we specify only one format, some programs would complain when you try to paste. So I added an `Auto` option to store as many as possible formats into clipboard.

![image](https://user-images.githubusercontent.com/2255715/126868003-20fcc6eb-9af9-48a0-aed0-4324319d7680.png)

There are four possible values:
* Auto
  Store as many as possible formats into clipboard.
* PNG
  Store only PNG into clipboard.
* JPEG
  Store only JPEG into clipboard.
* BMP
  Store only BMP into clipboard.

Because there are many different systems, no one of the above could make clipboard working all platforms. Users should try each of them to see if it works as expected.

2021-07-24 12:58 UTC, borgmanJeremy commented
Is there a reason this is wayland only?

2021-07-24 13:10 UTC, thetaprimeprime commented
> Is there a reason this is wayland only

Because the old option `useJpgForClipboard` only affects Wayland. Since I extend this function, I think it is still wayland only.

2021-07-31 17:38 UTC, borgmanJeremy requested changes

2021-07-31 17:38 UTC, borgmanJeremy commented on src/config/generalconf.cpp
> +    m_clipboardFormat->setToolTip(tr("Clipboard foramt (only for Wayland)"));
Can you fix typo in "format"

2021-07-31 17:38 UTC, borgmanJeremy commented on src/config/generalconf.cpp
> +    QGroupBox* box = new QGroupBox(tr("Clipboard foramt (only for Wayland)"));
typo in "format"

2021-07-31 17:38 UTC, borgmanJeremy commented on src/utils/screenshotsaver.cpp
> +    if (DesktopInfo().waylandDectected()) {
Let's allow this on X or Wayland. I think it should work on both.

2021-08-02 22:32 UTC, closed without merging