Customizable ColorPicker
flameshot-org/flameshot pull request #2202
Opened 2021-12-29 11:44 UTC by deo002

Closes #1942

## Functionality added:
- Select preset from colorpicker using spinbox.
- Press Delete to remove that preset from colorpicker.
- Choose color from color-wheel or enter it manually.
- Press Add to add that preset to colorpicker.

2021-12-31 02:37 UTC, borgmanJeremy commented
Thanks, this looks really good for a first pass. Since it touches so many place in the code and we are very close to the version 11 release I will wait to merge this until after the release.

Some comments based on testing (haven't done code review yet).
- If I add too many colors I get an error that says "Unable to add preset". This should probably state that the error stems from a cap on how many colors can be added.
- I think we should increase the number of colors to match the number that was added in #2171. @thepurple I think then we could remove the build flag for the pallet size. How does that sound?
- It would be nice if there were arrows or something that let you re-order the colors. This could be added in a future PR, not a blocking issue.

2021-12-31 08:09 UTC, deo002 commented
Thanks @borgmanJeremy! Third one would be a really nice addition.

2022-01-04 08:23 UTC, thepurple commented
@borgmanJeremy it sounds great, thx.

2022-01-26 18:46 UTC, borgmanJeremy commented
Okay the version 11 issues are slowing down so I am ready to look at this / merge. Can you remind me where it left off? We just need to do a code review and some testing?

2022-01-27 09:00 UTC, deo002 commented
@borgmanJeremy Yep, testing and code review are left. 
Some changes were suggested too. I will implement them along with the changes you would suggest in the code review. 
Thanks!

2022-01-28 18:36 UTC, borgmanJeremy requested changes
Thank you this is a great feature! 

I had some very minor comments. I had to fix some merge conflicts to do my testing but it was pretty easy. 

I'll get this merged quickly once the comments are addressed.

2022-01-28 18:36 UTC, borgmanJeremy commented on src/widgets/colorpickerwidget.cpp
> +        highlight.moveTo(highlight.x() - 3, highlight.y() - 3);
Why is this "-3"? Maybe 3 as a const variable with a descriptive name so its easier to read in the future?

2022-01-28 18:36 UTC, borgmanJeremy commented on src/widgets/colorpickerwidget.cpp
> +        highlight.setWidth(highlight.width() + 6);
Same question on 6

2022-01-28 18:36 UTC, borgmanJeremy commented on src/widgets/spinbox.cpp
> +SpinBox::SpinBox(QWidget* parent)
Im not sure SpinBox is the best name for this. Maybe put something in the name about what makes it different from a normal spin box? Like ColorSpinBox or something

2022-01-28 18:36 UTC, borgmanJeremy commented on src/config/colorpickereditor.cpp
> +    const int maxPresetsAllowed = 10;
Make this maximum match #2171 so we can remove this compile time option.

2022-01-28 18:36 UTC, borgmanJeremy commented on src/config/colorpickereditor.cpp
> +        QMessageBox::critical(this, tr("Error"), tr("Unable to add preset."));
Adjust this error to state why the preset cannot be added "IE exceeded maximum" or something.

2022-01-28 18:36 UTC, borgmanJeremy commented on src/config/colorpickereditor.cpp
> +          this, tr("Error"), tr("Unable to remove preset."));
Adjust this to say why it cannot be removed.

2022-01-30 13:36 UTC, deo002 commented
Thanks for feedback! I have pushed a fix addressing all the changes. @borgmanJeremy

2022-01-30 19:03 UTC, merged

2022-01-30 19:03 UTC, borgmanJeremy commented
Thanks!