Copy path to clipboard using native separators
flameshot-org/flameshot pull request #3136
Opened 2023-03-19 14:39 UTC by petrucianno

This pull request fixes issue #3135

2023-04-05 08:33 UTC, mmahmoudian commented
Thanks, looks good to me. I still rather another dev review it, but I add it to next release milestone.

2023-06-28 19:15 UTC, panpuchkov commented
It looks good, make it run without issues (clang-format) and we can merge it.
Sorry for the late response.

2023-08-20 18:46 UTC, veracioux requested changes

2023-09-14 15:40 UTC, veracioux commented
@petrucianno Thanks for the change. Did you run clang-format again? The clang-format Github action is failing.

2023-09-16 11:49 UTC, merged