Fix update cis
flameshot-org/flameshot pull request #3587
Opened 2024-04-28 18:51 UTC by mmahmoudian

I've updated everything to the latest minor or major version depending on if they have their major version tag following their latest stable minor version tag or not.

I have kept the `actions/upload-artifact` back in v3 because:
1. It seems there are breaking changes between `v3` -> `v4` ([more info](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md))
2. there is a PR (#3586) that have tried to update this for the Windows CI, so I would not change it to avoid duplicate and confusion

2024-04-29 11:15 UTC, Saibamen requested changes

2024-04-29 11:15 UTC, Saibamen commented on .github/workflows/Linux-pack.yml
> +        uses: snapcore/action-build@v1.2.0
```suggestion
        uses: snapcore/action-build@v1
```

`v1` will install latest v1 version ;)

2024-04-29 11:15 UTC, Saibamen commented on .github/workflows/Windows-pack.yml
> +        uses: lukka/run-vcpkg@v11.5
```suggestion
        uses: lukka/run-vcpkg@v11
```

2024-04-29 11:15 UTC, Saibamen commented on .github/workflows/Windows-pack.yml
> +        uses: jurplel/install-qt-action@v3.3.0
```suggestion
        uses: jurplel/install-qt-action@v3
```

2024-04-29 11:15 UTC, Saibamen commented on .github/workflows/build_cmake.yml
> +        uses: jurplel/install-qt-action@v3.3.0
```suggestion
        uses: jurplel/install-qt-action@v3
```

2024-04-29 11:54 UTC, mmahmoudian commented
@Saibamen It is not clear in [the Github documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses) if there is a difference between `@v4` and `@v4.3.2`. Bascially if `@v4` means `4.0.0` tag or `4` tag, or latest of `4.x.x` tags.

In some workflows, they move their major version tag to the latest minor version (e.g `v1` always updated to the latest of `v1.x.x`: https://github.com/snapcore/action-build/tags ), but this does not happen in all workflows (e.g.  https://github.com/jurplel/install-qt-action/tags )

Do you know how for example the `@v4` is handled by Github Actions?

2024-05-07 08:31 UTC, Saibamen commented
You can use https://github.com/saadmk11/github-actions-version-updater

2024-07-29 13:12 UTC, holazt commented
`actions/upload-artifact` v4 can't merge artifacts with the same name, v3 can. Nevertheless I think you can update `actions/upload-artifact` to v4, but you'll need to change the artifacts name, e.g. add some architecture or distribution information.

2025-04-27 14:27 UTC, borgmanJeremy commented
@mmahmoudian I think this conflicts with other PR's that were merged. Is there still work to do on this or should it be closed?

2025-04-27 14:51 UTC, closed without merging