Added release notes
flameshot-org/flameshot pull request #937
Opened 2020-09-18 15:36 UTC by borgmanJeremy

2020-09-18 15:47 UTC, hosiet requested changes
I believe there are several grammar errors in the "Known Issues" part. Please consider fixing them.

Besides, it's worthwhile to point out the actual format of "generic packages" by listing out their names (AppImage, Snap, etc.).

2020-09-18 16:04 UTC, mmahmoudian requested changes

2020-09-18 16:04 UTC, mmahmoudian commented on docs/ReleaseNotes.md
> +A button has been added to open the sidebar. This tool was previously only accessible by hitting "Spacebar" which made usage on tablets difficult. This sidebar allows advanced modifications for many
This looks like to be a duplicate of lines 46 and 47

2020-09-18 16:10 UTC, borgmanJeremy reviewed
Sorry I didnt see you made the edits directly until I had already pushed the fix.

2020-09-19 08:39 UTC, ZetaoYang commented on docs/ReleaseNotes.md
> +* In generic packages(Snap, Flatpak, AppImage) due to confinement "Open With External Application" does not work.
AppImage "Open With External Application" works fine, reference https://github.com/flameshot-org/flameshot/issues/933#issuecomment-694779370.

2020-09-19 08:46 UTC, ZetaoYang commented on docs/ReleaseNotes.md
> +* If close after capture is enabled, and a user copies the image to clipboard, the image may not actually be in the clipboard. We recommend using the "Save" feature with close after capture.
I suggest putting `close after capture` in quotation marks. -> "close after capture"

2020-09-19 08:52 UTC, ZetaoYang commented on docs/ReleaseNotes.md
> +  - Slovak (#525)
Some languages are not mentioned here yet, so please update it according to this list https://github.com/flameshot-org/translation-instruction#status .

2020-09-19 08:59 UTC, ZetaoYang requested changes
Please check out my two comments.

2020-09-19 15:35 UTC, hosiet approved these changes
Now this looks okay to me.

2020-09-19 16:01 UTC, ZetaoYang approved these changes
Now it's ok to me.

2020-09-19 18:49 UTC, merged